Bsky/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp" #appname을 명시하여 경로를 편리하게 설정할 수 있다.


urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = "articleapp" #appname을 명시하여 경로를 편리하게 설정할 수 있다.

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareL';">
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="Bsky_footer">
    <div class="Bsky_footer_button";">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top : 1rem;">
        <h6 class="Bsky_logo">Bsky</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Bsky</title>

    <!--BOOTSTRAP LINK-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!--Google FONT LINK-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Dosis:wght@200&display=swap" rel="stylesheet">

    <!--DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!--Local Font-->
    <style>
        @font-face {
            font-family: 'NanumSquareB.otf';
            src: local('NanumSquareB),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
            }
        @font-face {
            font-family: 'NanumSquareEB.otf';
            src: local('NanumSquareEB),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
            }
        @font-face {
            font-family: 'NanumSquareL.otf';
            src: local('NanumSquareL),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
            }
        @font-face {
            font-family: 'NanumSquareR.otf';
            src: local('NanumSquareR),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
            }
    </style>


</head>

templates/header.html
<div class="Bsky_header">
    <div class="Bsky_logo">
        <h1>Bsky</h1>
    </div>
    <div>
        <a href="{% url 'articleapp:list' %}">
                <span>Articles</span>
            </a>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <!--?next=={{request.path}} 구문을 통하여 login, logout을 하고난 뒤에 현재 페이지로 연결 할 수 있다.-->
                <!--이전 페이지의 경로를 url뒤에 붙여서 연결해주는식 ex > account/login/?next=/account/hello_world/-->
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}">
                <span>SignUp</span>
            </a>
        {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk%}">
                <span>MyPage</span>
            </a>
           <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span>logout</span>
            </a>
        {% endif %}
    </div>
</div>